# Number of simulation years
500
# Number of simulations
5
# Emsy_min Emsy_max
       0.3      0.7
# FractionMin FractiomMax
0.05 0.15                     #    0.05  0.15
# Cutoff 
150000
# Maxcatch
200000
# OFL option (0=Only Emsymin; 1=Increasing Emsy; 2=Emsy is temp-dependent); Override OFL (1=True)
2 0
# HG option (1=HG=Emsy; 2=HG=HG no temp; 3= HG=HG with temp)
3
# Cutoff option
0
# Buffer for P*; Max value for OFL
0.90592  0.241
# Seeds
-39948 -35946 -97996 -99182
# Sensitivity option: Time varying selectivities
0
# Sensitivity option: Multiple fleets
0
# F for Mexico and Canada 
0.2 0.1
# Sensitivity: hyper-stable estimates
0 500
# Sensitivity: Time varying natural mortaility
0
# Output selectivity
0
# Use annual SST instead of three year average
0
# Sensitivity: What selectivity to use (0=base, 1=Mex, 2=PNW)
0
